#!/bin/bash

set -x

set -eo pipefail

# Setup environment, including login.

. /opt/workshop/bin/setup-environ.sh

# Run startup actions if supplied.

if [ -x /opt/app-root/etc/init.d/rc.local ]; then
    /opt/app-root/etc/init.d/rc.local
fi

# Run workshop specific initialisation.

if [ -x /opt/app-root/src/.workshop/setup ]; then
    /opt/app-root/src/.workshop/setup
fi

# Run supervisord.

exec supervisord --nodaemon \
    --configuration /opt/workshop/etc/supervisord.conf
